"""add sleep_apnea_events table

Revision ID: 42b73e081090
Revises: 6d92c630e55d
Create Date: 2025-10-27 20:03:39.063554

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42b73e081090'
down_revision = '6d92c630e55d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_apnea_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('sleep_segment_id', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate_drop', sa.Float(), nullable=True),
    sa.Column('heart_rate_spike', sa.Float(), nullable=True),
    sa.Column('hrv_change', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('detected_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_apnea_events')
    # ### end Alembic commands ###
