"""init db

Revision ID: 6d92c630e55d
Revises: 
Create Date: 2025-10-26 00:30:20.137071

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6d92c630e55d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heart_rate',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heart_rate_variability',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respiratory_rate',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_analysis',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_duration_goal',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vo_2_max',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heart_rate_variability_bpm',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('hr_variability_id', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hr_variability_id'], ['heart_rate_variability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heart_rate_variability_bpm')
    op.drop_table('vo_2_max')
    op.drop_table('sleep_duration_goal')
    op.drop_table('sleep_analysis')
    op.drop_table('respiratory_rate')
    op.drop_table('heart_rate_variability')
    op.drop_table('heart_rate')
    # ### end Alembic commands ###
