"""add ingestion staging and unique constraints

Revision ID: bc2a4f91c8de
Revises: 5afc1f597bdb
Create Date: 2026-02-26 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc2a4f91c8de"
down_revision = "5afc1f597bdb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "xml_uploads",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_xml", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_xml_uploads_sha256"),
    )

    op.create_table(
        "raw_health_records",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(), nullable=False),
        sa.Column("sourceName", sa.String(), nullable=True),
        sa.Column("creationDate", sa.DateTime(), nullable=True),
        sa.Column("startDate", sa.DateTime(), nullable=True),
        sa.Column("endDate", sa.DateTime(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["upload_id"], ["xml_uploads.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        """
        DO $$
        DECLARE
            has_identity boolean;
        BEGIN
            SELECT (a.attidentity <> '')
            INTO has_identity
            FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public'
              AND c.relname = 'sleep_apnea_events'
              AND a.attname = 'id'
              AND a.attnum > 0
              AND NOT a.attisdropped;

            IF has_identity IS FALSE THEN
                EXECUTE 'ALTER TABLE sleep_apnea_events ALTER COLUMN id DROP DEFAULT';
                EXECUTE 'ALTER TABLE sleep_apnea_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;
        END $$;
        """
    )

    op.execute(
        """
        DELETE FROM heart_rate a
        USING heart_rate b
        WHERE a.id > b.id
          AND a."sourceName" = b."sourceName"
          AND a."startDate" = b."startDate"
          AND a."endDate" = b."endDate";
        """
    )
    op.execute(
        """
        DELETE FROM heart_rate_variability a
        USING heart_rate_variability b
        WHERE a.id > b.id
          AND a."sourceName" = b."sourceName"
          AND a."startDate" = b."startDate"
          AND a."endDate" = b."endDate";
        """
    )
    op.execute(
        """
        DELETE FROM respiratory_rate a
        USING respiratory_rate b
        WHERE a.id > b.id
          AND a."sourceName" = b."sourceName"
          AND a."startDate" = b."startDate"
          AND a."endDate" = b."endDate";
        """
    )
    op.execute(
        """
        DELETE FROM vo_2_max a
        USING vo_2_max b
        WHERE a.id > b.id
          AND a."sourceName" = b."sourceName"
          AND a."startDate" = b."startDate"
          AND a."endDate" = b."endDate";
        """
    )
    op.execute(
        """
        DELETE FROM sleep_analysis a
        USING sleep_analysis b
        WHERE a.id > b.id
          AND a."sourceName" = b."sourceName"
          AND a."startDate" = b."startDate"
          AND a."endDate" = b."endDate";
        """
    )
    op.execute(
        """
        DELETE FROM sleep_duration_goal a
        USING sleep_duration_goal b
        WHERE a.id > b.id
          AND a."sourceName" = b."sourceName"
          AND a."startDate" = b."startDate"
          AND a."endDate" = b."endDate";
        """
    )
    op.execute(
        """
        DELETE FROM heart_rate_variability_bpm a
        USING heart_rate_variability_bpm b
        WHERE a.id > b.id
          AND a.hr_variability_id = b.hr_variability_id
          AND a.time = b.time;
        """
    )

    op.create_unique_constraint("uq_sleep_analysis_record", "sleep_analysis", ["sourceName", "startDate", "endDate"])
    op.create_unique_constraint("uq_sleep_duration_goal_record", "sleep_duration_goal", ["sourceName", "startDate", "endDate"])
    op.create_unique_constraint("uq_heart_rate_record", "heart_rate", ["sourceName", "startDate", "endDate"])
    op.create_unique_constraint("uq_hrv_record", "heart_rate_variability", ["sourceName", "startDate", "endDate"])
    op.create_unique_constraint("uq_hrv_bpm_record", "heart_rate_variability_bpm", ["hr_variability_id", "time"])
    op.create_unique_constraint("uq_respiratory_rate_record", "respiratory_rate", ["sourceName", "startDate", "endDate"])
    op.create_unique_constraint("uq_vo2max_record", "vo_2_max", ["sourceName", "startDate", "endDate"])
    op.create_unique_constraint("uq_sleep_apnea_event", "sleep_apnea_events", ["start_time", "end_time", "detected_by"])


def downgrade() -> None:
    op.drop_constraint("uq_sleep_apnea_event", "sleep_apnea_events", type_="unique")
    op.drop_constraint("uq_vo2max_record", "vo_2_max", type_="unique")
    op.drop_constraint("uq_respiratory_rate_record", "respiratory_rate", type_="unique")
    op.drop_constraint("uq_hrv_bpm_record", "heart_rate_variability_bpm", type_="unique")
    op.drop_constraint("uq_hrv_record", "heart_rate_variability", type_="unique")
    op.drop_constraint("uq_heart_rate_record", "heart_rate", type_="unique")
    op.drop_constraint("uq_sleep_duration_goal_record", "sleep_duration_goal", type_="unique")
    op.drop_constraint("uq_sleep_analysis_record", "sleep_analysis", type_="unique")

    op.execute("ALTER TABLE sleep_apnea_events ALTER COLUMN id DROP IDENTITY IF EXISTS")

    op.drop_table("raw_health_records")
    op.drop_table("xml_uploads")
