BASELINE_MAX_DAYS = 60
RECENT_DAYS = 5
MIN_VALID_DAYS_FOR_SIGNAL = 45
MIN_RECENT_VALID_DAYS = 3
ILLNESS_TREND_LOOKBACK_DAYS = 63
HR_POINTS_PER_DAY_MIN = 12
HRV_POINTS_PER_DAY_MIN = 3

# Wrist temperature integration (Apple Watch 8+)
TEMP_MIN_BASELINE_NIGHTS = 5
TEMP_RECENT_NIGHTS = 2
TEMP_MAX_BASELINE_NIGHTS = 14
